changelog:
  exclude:
    labels:
      - ignore
  categories:
    - title: ⚠️ Breaking Changes and Deprecations
      labels:
        - breaking-change
        - deprecation
    - title: 🎉 New Features
      labels:
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bug
    - title: 🔒 Security
      labels:
        - security
    - title: ⚙️ Other Changes
      labels:
        - "*"