version: "2"
run:
  modules-download-mode: readonly
linters:
  enable:
    - copyloopvar
    - durationcheck
    - forcetypeassert
    - godot
    - makezero
    - misspell
    - nilerr
    - predeclared
    - unconvert
    - unparam
  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
