run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - copyloopvar
    - durationcheck
    - errcheck
    - forcetypeassert
    - godot
    - goimports
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - tenv
    - unconvert
    - unparam
    - unused

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0


linters-settings:
  errcheck:
    exclude-functions:
      - (io.Closer).Close # Safe to exclude for closing HTTP response bodies in memory