name: Labels
on:
    pull_request:
        types:
            - opened
            - labeled
            - unlabeled
jobs:
    check:
        name: Require Label
        runs-on: ubuntu-latest
        if: join(github.event.pull_request.labels) == ''