name: Labels
on:
    pull_request:
        types:
            - opened
            - labeled
            - unlabeled
jobs:
    check:
        name: Require Label
        uses: actions/github-script@v7
        with:
            script: |
                if (join(github.event.pull_request.labels) === '' {
                    core.setFailed('at least one label is required')
                }