name: Labels
on:
    pull_request:
        types:
            - opened
            - labeled
            - unlabeled
jobs:
    check:
        runs-on: ubuntu-latest
        name: Require Label
        steps:
            - uses: actions/github-script@v7
              with:
                  script: |
                    const pr = await github.rest.pulls.get({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        pull_number: context.issue.number
                    })

                    const labels = pr["labels"]

                    for (const label of labels) {
                        console.log(label["name"])
                    }