name: Labels
on:
    pull_request:
        types:
            - opened
            - labeled
            - unlabeled
jobs:
    check:
        runs-on: ubuntu-latest
        name: Require Label
        steps:
            - uses: actions/github-script@v7
              with:
                  script: |
                    console.log(context.payload.pull_request.labels.length + "labels applied")
