name: Test
on:
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
            - ready_for_review
jobs:
    golangci-lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: golangci/golangci-lint-action@v6
              with:
                version: latest
    